language: python
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --editable .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
